# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_temp', models.IntegerField()),
                ('bean_temp', models.IntegerField()),
                ('loft_setting', models.FloatField()),
                ('heat_setting', models.FloatField()),
                ('event', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='datapoint',
            name='roast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorder.Roast'),
        ),
    ]
