# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='roast_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='bean_temp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='element_temp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='event',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='heat_setting',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='loft_setting',
            field=models.FloatField(blank=True),
        ),
    ]
