# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0003_auto_20180308_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
